name: Continuous Integration
on: [push]
jobs:
  check-rdf-file-availability:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.3"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"
      - name: Install Composer dependencies
        run: cd scripts && composer update --no-progress --prefer-dist --optimize-autoloader
      # check availability of RDF files used in ontologies.csv
      - name: "Run checks"
        run: "php scripts/bin/check-availability-of-rdf-files"
  check_latext_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      # Linter to validate our CSV file
      - name: Run csv-lint
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          file_list: "ontologies.csv"
          find_pattern: "*.csv"
          find_path: "./"
          fail_on_error: "true"
